### ISSUE TITLE
what do we mean by unary?

### ISSUE THREAD

**Issue by seyeeet** [kazuto1011/deeplab-pytorch#104]
can you please tell me what does unary map (here        [ U = utils.unary_from_softmax(probmap)](https://github.com/kazuto1011/deeplab-pytorch/blob/master/libs/utils/crf.py) ) should look like? is it like binary map?

I guess my question is more fundamental, like what is unary map? :)

thanks

**Comment by kazuto1011** [comment]
The function just computes a negative logarithm of the class probability map for a computational reason. The unary map is like a prior of pixel attributes. CRF updates/smoothens the prior based on the spatial continuity on RGB.

**Comment by seyeeet** [comment]
Thanks @kazuto1011
