### ISSUE TITLE
custom dataset

### ISSUE THREAD

**Issue by soans1994** [kazuto1011/deeplab-pytorch#105]
hello author,

how to build voc like data from custom dataset of raw images and seg masks png.

thank you

**Comment by kazuto1011** [comment]
The following explains how to create the custom dataset class, inheriting `libs.datasets.base._BaseDataset`. The class has no content in `_set_files()` and `_load_data()`, where you need to instantiate them for your case.

https://github.com/kazuto1011/deeplab-pytorch/blob/4219467fa5de07985f834f1bd8c04c186dc8f6d8/libs/datasets/base.py#L48-L58

1. Assuming a pair of image and label files is named with a unique ID, we then store all the IDs to a list `self.files` in `_set_files()`. For instance, `CocoStuff164k` extracts the IDs from image paths as follows.

https://github.com/kazuto1011/deeplab-pytorch/blob/4219467fa5de07985f834f1bd8c04c186dc8f6d8/libs/datasets/cocostuff.py#L64-L74

2. Next, we implement `_load_data()`, which reads and returns a pair of image and label data from the given `index` of the IDs. Again, `CocoStuff164k` may help you.

https://github.com/kazuto1011/deeplab-pytorch/blob/4219467fa5de07985f834f1bd8c04c186dc8f6d8/libs/datasets/cocostuff.py#L76-L84

That's all. The custom dataset class can fetch and preprocess the data, as implemented in the super class.

https://github.com/kazuto1011/deeplab-pytorch/blob/4219467fa5de07985f834f1bd8c04c186dc8f6d8/libs/datasets/base.py#L105-L113

**Comment by soans1994** [comment]
@kazuto1011 

thank you very much for the detailed explaination.
