### ISSUE TITLE
get_dataset

### ISSUE THREAD

**Issue by miao19980215** [kazuto1011/deeplab-pytorch#106]
Inside your main function there is a function that is not defined.can you tell me the origin of get_datasets？

**Comment by kazuto1011** [comment]
It is defined here
https://github.com/kazuto1011/deeplab-pytorch/blob/4219467fa5de07985f834f1bd8c04c186dc8f6d8/libs/datasets/__init__.py#L5-L11

**Comment by miao19980215** [comment]
Thank you, I'm not used to defining functions under that __init__.py. Thank you so much, I have no problem, I will ask again, a master student studying
