### ISSUE TITLE
the pre-trained model

### ISSUE THREAD

**Issue by woqiaow** [kazuto1011/deeplab-pytorch#107]
Hello, thank you for sharing the code. I have some problems in implementing the code.
In voc.yaml， the pre-trained caffemodel is data/models/coco/deeplabv1_resnet101/caffemodel/deeplabv1_resnet101-coco.pth， I want to ask whether this pre training model is used for training voc dataset？
![image](https://user-images.githubusercontent.com/106650655/194995602-81b7c76a-20ea-4660-8954-211593af31fc.png)
In addition, if I want to replace it with the ImageNet pre-trained model, can I directly change the path of the deeplabv1_resnet101-coco.pth  to the path of the ImageNet pre_trained model in voc.yaml?
I hope you can answer, thank you!

**Comment by kazuto1011** [comment]
Q: The pre-trained model is used for training VOC?
Yes, [the official DeepLab v2](http://liangchiehchen.com/projects/DeepLabv2_resnet.html) is also initialized on COCO and fine-tuned on Pascal VOC.
`deeplabv1_resnet101-coco.pth` is converted from the officially provided `init.caffemodel`.

Q: Can I directly change the path to replace the init model?
Yes, it's okay if your ImageNet weights are compatible with this repository re-implemented from the *Caffe* ResNet. For instance, *torchvision* ResNet is not compatible (#61, #67, #88).
You have an option of the on-the-fly modification (#33).

**Comment by woqiaow** [comment]
Thank you for your quick reply! Very clear.
