### ISSUE TITLE
How to train on the coco-stuff datasets?

### ISSUE THREAD

**Issue by xiaoningpi** [kazuto1011/deeplab-pytorch#115]
I want to train on the COCO-Stuff dataset. How can I do that

**Comment by kazuto1011** [comment]
Please follow [this setup instruction](https://github.com/kazuto1011/deeplab-pytorch#setup) and run `python main.py train --config-path configs/cocostuff164k.yaml`.
[A pre-trained model](https://github.com/kazuto1011/deeplab-pytorch#torchhub) is also available.
