### ISSUE TITLE
cuda error caused by negative tensor value

### ISSUE THREAD

**Issue by littlebelly** [kazuto1011/deeplab-pytorch#14]
Hi, thanks for your nice code again! But I got a wired error when run your code, error info as below:

`THCudaCheck FAIL file=/opt/conda/conTHC/generic/THCTensorCopy.c line=20 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "train.py", line 229, in <module>
    main()
  File "/data1/jayzjwang/opt/anaconda3/envs/deeplab/lib/python3.5/site-packages/click/core.py", line 
    return self.main(*args, **kwargs)
  File "/data1/jayzjwang/opt/anaconda3/envs/deeplab/lib/python3.5/site-packages/click/core.py", line 
    rv = self.invoke(ctx)
  File "/data1/jayzjwang/opt/anaconda3/envs/deeplab/lib/python3.5/site-packages/click/core.py", line 
    return ctx.invoke(self.callback, **ctx.params)
  File "/data1/jayzjwang/opt/anaconda3/envs/deeplab/lib/python3.5/site-packages/click/core.py", line 
    return callback(*args, **kwargs)
  File "train.py", line 183, in main
    target_ = target_.to(device)
RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_TensorCopy.c:20
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoad
Traceback (most recent call last):
  File "/data1/jayzjwang/opt/anaconda3/envs/deeplab/lib/python3.5/site-packages/torch/utils/data/data
    self._shutdown_workers()
  File "/data1/jayzjwang/opt/anaconda3/envs/deeplab/lib/python3.5/site-packages/torch/utils/data/data
    self.worker_result_queue.get()
  File "/data1/jayzjwang/opt/anaconda3/envs/deeplab/lib/python3.5/multiprocessing/queues.py", line 33
    return ForkingPickler.loads(res)
  File "/data1/jayzjwang/opt/anaconda3/envs/deeplab/lib/python3.5/site-packages/torch/multiprocessinge_fd
    fd = df.detach()
  File "/data1/jayzjwang/opt/anaconda3/envs/deeplab/lib/python3.5/multiprocessing/resource_sharer.py"
    with _resource_sharer.get_connection(self._id) as conn:
  File "/data1/jayzjwang/opt/anaconda3/envs/deeplab/lib/python3.5/multiprocessing/resource_sharer.py"
    c = Client(address, authkey=process.current_process().authkey)
  File "/data1/jayzjwang/opt/anaconda3/envs/deeplab/lib/python3.5/multiprocessing/connection.py", lin
    c = SocketClient(address)
  File "/data1/jayzjwang/opt/anaconda3/envs/deeplab/lib/python3.5/multiprocessing/connection.py", lin
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused`

it may be caused by negative tensor value when set ignore_label to -1 in preprocessing label map according to this issue torch/cutorch#708, after I set the ignore label to 255 (I make minor change to your codes to run it on voc12), it can work fine

**Comment by kazuto1011** [comment]
Let me confirm your modification. 

> it may be caused by negative tensor value when set ignore_label to -1 in preprocessing label map according to this issue torch/cutorch#708, after I set the ignore label to 255 (I make minor change to your codes to run it on voc12), it can work fine

Are you referring to [```config/voc12.yaml```](https://github.com/kazuto1011/deeplab-pytorch/blob/master/config/voc12.yaml#L21)? Or your dataloader for voc?
In cocostuff case, the negative value has never caused the runtime error in ```target_.to(device)```

**Comment by kazuto1011** [comment]
I have no idea why the ```target_ = target_.to(device)``` cased the runtime error.
Did the target tensor contain a negative value?
My guess is that it is possible that the label 255 in "target_" would be denied by the loss criterion (the next line) which assumes indices 0 to 20 for classes and another index -1 for "ignore label".
And I think it can be solved by changing the "ignore label" from -1 to 255 as you said.
Haven't you modified your code during training? (doubt for the stack trace, sorry)

**Comment by littlebelly** [comment]
I refered voc12.yaml in your config folder and I just add voc12.py in dataset folder as this file [voc12.py](https://gist.github.com/littlebelly/cef26b98fe8befc1408e16efaabe5de0)(L33-L34, L54, L147-L149, I don't know how to highlight multi lines in github, sorry for that) to load voc12 dataset, for train.py, I only change the dataset class to voc.

Btw, after training 20000 iters, I can get these miou results on voc12:
eval on single scale:  75.455%
eval on multi scale as original paper (0.5, 0.75, 1.0): 74.291%
eval on multi scale (0.75, 1.0, 1.25): 75.809%

The best score is still about 0.5% difference with the paper's result (76.35%), which is acceptable and I think the difference may caused by the reason that pytorch doesn't support synchronous batch normalization which can bring 0.5-0.6 difference on the final result in multi-gpu training process (my friend told me this information), and I found a sync bn implementation [here](https://github.com/vacancy/Synchronized-BatchNorm-PyTorch), but after I simply changed the bn layer in your model, the results was only about 74%, maybe I didn't make it on the right way, how do you think about it?
ps: I found another great segmentation repo [semantic-segmentation-pytorch](https://github.com/CSAILVision/semantic-segmentation-pytorch) which used the sync bn in pytorch, maybe it will be helpful

Thanks for your codes again!

**Comment by littlebelly** [comment]
here are some other files:
[train.py](https://gist.github.com/littlebelly/0594e6bd320b57750aa2b19d1d174309)
[eval.py](https://gist.github.com/littlebelly/517a34f5e8090f72ef7eeb425063133b)

**Comment by kazuto1011** [comment]
Anyway, I fixed ```config/voc12.yaml```. Thank you for the information about synchronous batch normalization! I didn't know that. I think that's crucial but, to be honest, have no idea how to solve your problem now. Let me close this issue because the bn problem is out of scope.
I will try to fix the problem, any PRs are welcome.

**Comment by LindaSt** [comment]
> I have no idea why the `target_ = target_.to(device)` cased the runtime error.
> Did the target tensor contain a negative value?
> My guess is that it is possible that the label 255 in "target_" would be denied by the loss criterion (the next line) which assumes indices 0 to 20 for classes and another index -1 for "ignore label".
> And I think it can be solved by changing the "ignore label" from -1 to 255 as you said.
> Haven't you modified your code during training? (doubt for the stack trace, sorry)

Why can the tensors not contain any negative values?
