### ISSUE TITLE
A issue related the testing crop size

### ISSUE THREAD

**Issue by PkuRainBow** [kazuto1011/deeplab-pytorch#16]
I find that you choose a small center crop for testing, thus you are not computing the mIou over the whole image, thus I am wondering this is wrong or this is a standard operation for coco-stuff dataset.

**Comment by kazuto1011** [comment]
My testing code doesn't crop images but warp them to square-shape at first.
https://github.com/kazuto1011/deeplab-pytorch/blob/master/libs/datasets/cocostuff.py#L144
COCO-Stuff instruction to resize images.
https://github.com/nightrome/cocostuff10k#deeplab-resnet-101

**Comment by PkuRainBow** [comment]
@kazuto1011 So do you warp the label maps?  If so, my concern is that the reported performance is not comparable with the official results as you evaluate the warped label maps.

**Comment by kazuto1011** [comment]
The authors first warped images and labels to a fixed 513x513 size both in training and testing. And then they fed them into the official deeplab codes. I thought the reported score was computed with the pre-warped annotations and the up-sampled label maps in 513x513. Any missed steps? Do you concern about a warped annotation different from the raw?

**Comment by kazuto1011** [comment]
I’m not sure about the latest cvpr paper. I followed the steps in the previous official page (cocostuff10k).
