### ISSUE TITLE
Download link to trained model?

### ISSUE THREAD

**Issue by isht7** [kazuto1011/deeplab-pytorch#18]
Hi @kazuto1011 ,
Thank you for making your code public.
I was hoping that you would put a download link of your trained model in the readme so that people can use it without training themselves. 
Thanks!

**Comment by kazuto1011** [comment]
I agree. I will upload the trained model soon.

**Comment by isht8** [comment]
@kazuto1011 any update? I was hoping to get the trained model.

**Comment by kazuto1011** [comment]
Updated
