### ISSUE TITLE
Train with COCO-Stuff 164K

### ISSUE THREAD

**Issue by nightrome** [kazuto1011/deeplab-pytorch#22]
Hi. With your permission I'd love to recommend this repo on the [COCO-Stuff page](https://github.com/nightrome/cocostuff). Do you think you could train it on the train set of COCO-Stuff 164K and provide that model? That should also significantly boost the performance. Let me know if you have further questions.

**Comment by kazuto1011** [comment]
Finally I got results on COCO-Stuff 164k. Could you verify whether those results are acceptable? I can't run the official DeepLab. Basically I just only changed the number of iterations to 100k.

Results on the val set of COCO-Stuff **164k** (```val2017/*.jpg```), without crf:

||Class accuracy|Pixel accuracy|Mean IOU|FW IOU|
|:-:|:-:|:-:|:-:|:-:|
|DeepLab v2|49.8%|65.6%|37.7%|50.1%|

Results on the val set of COCO-Stuff **10k** (```test.txt```), without crf:

||Class accuracy|Pixel accuracy|Mean IOU|FW IOU|
|:-:|:-:|:-:|:-:|:-:|
|DeepLab v2|45.1%|64.8%|33.8%|50.1%|

**Comment by nightrome** [comment]
Fantastic! I ran the offical Deeplab v2 VGG16 [here](https://github.com/nightrome/cocostuff#results) and got 33.2% MIOU on 164K. And 34.4% for Deeplab v2 ResNet on 10K. So your results are both reasonable and good! Maybe you could also add the CRF?
In any case, if you put the numbers and model on your start page, I'll link to them from https://github.com/nightrome/cocostuff

**Comment by kazuto1011** [comment]
Updated [README](https://github.com/kazuto1011/deeplab-pytorch#performance) with CRF results and a link to download trained model.

**Comment by nightrome** [comment]
Great! I've linked to your repo at: https://github.com/nightrome/cocostuff/blob/master/README.md#semantic-segmentation-models-stuffthings
