### ISSUE TITLE
Missing keys in state_dict

### ISSUE THREAD

**Issue by chenyanghungry** [kazuto1011/deeplab-pytorch#26]
I try to run cocostuff pretrained model on a voc12 image using demo.py.  After converting  caffemodel of coco into pytorch model, there arises an error when runing demo.py  in line 57 , which is   model.load_state_dict(state_dict) .

RuntimeError: Error in loading state_dict for MSC:
      Missing key(s) in state_dict : "scale.aspp.stages.c0.bias"  , "scale.aspp.stages.c0.weight" ,"scale.aspp.stages.c1.bias" , "scale.aspp.stages.c1.weight" , "scale.aspp.stages.c2.bias" , "scale.aspp.stages.c2.weight" , "scale.aspp.stages.c3.bias" , "scale.aspp.stages.c3.weight". 

and when  I look for display information when converting coco_init caffemodel into .pth file ,  indeed I don't see any related information too. It seems there is no scale.aspp related layers' parameters.    I don't know why and how to solve this issue. Thanks!

**Comment by kazuto1011** [comment]
The final layer of the coco_init model is a bit different from the one for ```demo.py```. The model is just for initial parameters in ```train.py``` and the final layer is ignored like:
https://github.com/kazuto1011/deeplab-pytorch/blob/fca8bc893df96f8a61553e7ae0ff36827b5d77d3/train.py#L107
Instead of the coco_init model, please use the any one of three models below for ```demo.py```:
* COCO-Stuff model generated from ```train.py```
* Pre-trained COCO-Stuff model provided [here](https://github.com/kazuto1011/deeplab-pytorch#performance)
* Pre-trained VOC 2012 model (```python convert.py --dataset voc12```)

**Comment by chenyanghungry** [comment]
thanks a lot ! now I use cocostuff.caffemodel to train, not init_coco.caffemodel , it helps.~~ thanks again~

**Comment by ra1995** [comment]
Hi,
I am trying to run the demo with the COCO-Stuff model (pretrained 164k from the drive link). I am getting the following error:

`RuntimeError: Error(s) in loading state_dict for MSC:
	Unexpected key(s) in state_dict: "scale.layer1.conv1.bn.num_batches_tracked", "scale.layer2.block1.reduce.bn.num_batches_tracked", "scale.layer2.block1.conv3x3.bn.num_batches_tracked", "scale.layer2.block1.increase.bn.num_batches_tracked", "scale.layer2.block1.proj.bn.num_batches_tracked", "scale.layer2.block2.reduce.bn.num_batches_tracked", "scale.layer2.block2.conv3x3.bn.num_batches_tracked", "scale.layer2.block2.increase.bn.num_batches_tracked", "scale.layer2.block3.reduce.bn.num_batches_tracked", "scale.layer2.block3.conv3x3.bn.num_batches_tracked", "scale.layer2.block3.increase.bn.num_batches_tracked", "scale.layer3.block1.reduce.bn.num_batches_tracked", "scale.layer3.block1.conv3x3.bn.num_batches_tracked", "scale.layer3.block1.increase.bn.num_batches_tracked", "scale.layer3.block1.proj.bn.num_batches_tracked", "scale.layer3.block2.reduce.bn.num_batches_tracked", "scale.layer3.block2.conv3x3.bn.num_batches_tracked", "scale.layer3.block2.increase.bn.num_batches_tracked", "scale.layer3.block3.reduce.bn.num_batches_tracked", "scale.layer3.block3.conv3x3.bn.num_batches_tracked", "scale.layer3.block3.increase.bn.num_batches_tracked", "scale.layer3.block4.reduce.bn.num_batches_tracked", "scale.layer3.block4.conv3x3.bn.num_batches_tracked", "scale.layer3.block4.increase.bn.num_batches_tracked", "scale.layer4.block1.reduce.bn.num_batches_tracked", "scale.layer4.block1.conv3x3.bn.num_batches_tracked", "scale.layer4.block1.increase.bn.num_batches_tracked", "scale.layer4.block1.proj.bn.num_batches_tracked", "scale.layer4.block2.reduce.bn.num_batches_tracked", "scale.layer4.block2.conv3x3.bn.num_batches_tracked", "scale.layer4.block2.increase.bn.num_batches_tracked", "scale.layer4.block3.reduce.bn.num_batches_tracked", "scale.layer4.block3.conv3x3.bn.num_batches_tracked", "scale.layer4.block3.increase.bn.num_batches_tracked", "scale.layer4.block4.reduce.bn.num_batches_tracked", "scale.layer4.block4.conv3x3.bn.num_batches_tracked", "scale.layer4.block4.increase.bn.num_batches_tracked", "scale.layer4.block5.reduce.bn.num_batches_tracked", "scale.layer4.block5.conv3x3.bn.num_batches_tracked", "scale.layer4.block5.increase.bn.num_batches_tracked", "scale.layer4.block6.reduce.bn.num_batches_tracked", "scale.layer4.block6.conv3x3.bn.num_batches_tracked", "scale.layer4.block6.increase.bn.num_batches_tracked", "scale.layer4.block7.reduce.bn.num_batches_tracked", "scale.layer4.block7.conv3x3.bn.num_batches_tracked", "scale.layer4.block7.increase.bn.num_batches_tracked", "scale.layer4.block8.reduce.bn.num_batches_tracked", "scale.layer4.block8.conv3x3.bn.num_batches_tracked", "scale.layer4.block8.increase.bn.num_batches_tracked", "scale.layer4.block9.reduce.bn.num_batches_tracked", "scale.layer4.block9.conv3x3.bn.num_batches_tracked", "scale.layer4.block9.increase.bn.num_batches_tracked", "scale.layer4.block10.reduce.bn.num_batches_tracked", "scale.layer4.block10.conv3x3.bn.num_batches_tracked", "scale.layer4.block10.increase.bn.num_batches_tracked", "scale.layer4.block11.reduce.bn.num_batches_tracked", "scale.layer4.block11.conv3x3.bn.num_batches_tracked", "scale.layer4.block11.increase.bn.num_batches_tracked", "scale.layer4.block12.reduce.bn.num_batches_tracked", "scale.layer4.block12.conv3x3.bn.num_batches_tracked", "scale.layer4.block12.increase.bn.num_batches_tracked", "scale.layer4.block13.reduce.bn.num_batches_tracked", "scale.layer4.block13.conv3x3.bn.num_batches_tracked", "scale.layer4.block13.increase.bn.num_batches_tracked", "scale.layer4.block14.reduce.bn.num_batches_tracked", "scale.layer4.block14.conv3x3.bn.num_batches_tracked", "scale.layer4.block14.increase.bn.num_batches_tracked", "scale.layer4.block15.reduce.bn.num_batches_tracked", "scale.layer4.block15.conv3x3.bn.num_batches_tracked", "scale.layer4.block15.increase.bn.num_batches_tracked", "scale.layer4.block16.reduce.bn.num_batches_tracked", "scale.layer4.block16.conv3x3.bn.num_batches_tracked", "scale.layer4.block16.increase.bn.num_batches_tracked", "scale.layer4.block17.reduce.bn.num_batches_tracked", "scale.layer4.block17.conv3x3.bn.num_batches_tracked", "scale.layer4.block17.increase.bn.num_batches_tracked", "scale.layer4.block18.reduce.bn.num_batches_tracked", "scale.layer4.block18.conv3x3.bn.num_batches_tracked", "scale.layer4.block18.increase.bn.num_batches_tracked", "scale.layer4.block19.reduce.bn.num_batches_tracked", "scale.layer4.block19.conv3x3.bn.num_batches_tracked", "scale.layer4.block19.increase.bn.num_batches_tracked", "scale.layer4.block20.reduce.bn.num_batches_tracked", "scale.layer4.block20.conv3x3.bn.num_batches_tracked", "scale.layer4.block20.increase.bn.num_batches_tracked", "scale.layer4.block21.reduce.bn.num_batches_tracked", "scale.layer4.block21.conv3x3.bn.num_batches_tracked", "scale.layer4.block21.increase.bn.num_batches_tracked", "scale.layer4.block22.reduce.bn.num_batches_tracked", "scale.layer4.block22.conv3x3.bn.num_batches_tracked", "scale.layer4.block22.increase.bn.num_batches_tracked", "scale.layer4.block23.reduce.bn.num_batches_tracked", "scale.layer4.block23.conv3x3.bn.num_batches_tracked", "scale.layer4.block23.increase.bn.num_batches_tracked", "scale.layer5.block1.reduce.bn.num_batches_tracked", "scale.layer5.block1.conv3x3.bn.num_batches_tracked", "scale.layer5.block1.increase.bn.num_batches_tracked", "scale.layer5.block1.proj.bn.num_batches_tracked", "scale.layer5.block2.reduce.bn.num_batches_tracked", "scale.layer5.block2.conv3x3.bn.num_batches_tracked", "scale.layer5.block2.increase.bn.num_batches_tracked", "scale.layer5.block3.reduce.bn.num_batches_tracked", "scale.layer5.block3.conv3x3.bn.num_batches_tracked", "scale.layer5.block3.increase.bn.num_batches_tracked".`

I am new to pytorch and don't know how to solve this issue.
Thanks

**Comment by kazuto1011** [comment]
What is your PyTorch version?

**Comment by dizzy77777** [comment]
I have the same problem as @ra1995.
My PyTorch version is 0.4.0. Is there a workaround for this problem with my PyTorch version? Thanks!

**Comment by ra1995** [comment]
Hi, I solved the problem by writing the following snippet, dont know what the exact issue was
`def setup_model(model_path, device, CONFIG):
    model = DeepLabV2_ResNet101_MSC(n_classes=CONFIG.N_CLASSES)
    state_dict = torch.load(model_path, map_location=lambda storage, loc: storage)
    model.load_state_dict(state_dict, strict=False)
    model.eval()
    model.to(device)
    return model`
`CONFIG = Dict(yaml.load(open('/media/rishabh/New Volume/rishabh/segmentation/deeplab-pytorch/config/cocostuff164k.yaml')))`

**Comment by kazuto1011** [comment]
The issue was due to that the previous PyTorch does not have `num_batches_tracked` in batch norm layer. As seen in your snippet, the `strict=False` option in `model.load_state_dict()` ignores the unknown parameters and solves the error above. That's why I asked the version.

**Comment by dizzy77777** [comment]
Thanks @ra1995 and @kazuto1011!, that worked for me. Unfortunately, if have now a problem with "torch.nn.functional.interpolate", since this function is not available in PyTorch 0.4.0. And my suggested way of using "torch.nn.functional.upsample" instead does not work because of the "float-scaling" of [0.5, 0.75] - upsample needs integer values for scaling. Any ideas how I can rewrite that?

**Comment by kazuto1011** [comment]
Looked back :)
https://github.com/kazuto1011/deeplab-pytorch/blob/2760e35a219fac54a3be86ee851d2697e24935e1/libs/models/msc.py#L28-L33

**Comment by dizzy77777** [comment]
Thanks @kazuto1011 works fine now!
