### ISSUE TITLE
Get "StopIteration" while training

### ISSUE THREAD

**Issue by albert18711** [kazuto1011/deeplab-pytorch#27]
Hi, thanks for the code

I got some problem at "python train.py --config config/cocostuff164k.yaml" part.
It pop out "StopIteration" error soon after the training process began.

Error message i get
============================================================
(deeplab-pytorch) b03901017@dcs02:~/DeepLab/v2/deeplab-pytorch$ python2 train.py --config config/cocostuff164k.yaml
Running on GeForce GTX 1080
/usr/local/lib/python2.7/dist-packages/torch/nn/functional.py:52: UserWarning: size_average and reduce args will be deprecated, please use reduction='elementwise_mean' instead.
  warnings.warn(warning.format(ret))
  0%|                                                                                                                                                          | 0/100000 [00:00<?, ?it/s]Exception KeyError: KeyError(<weakref at 0x7fb3542838e8; to 'tqdm' at 0x7fb354270f50>,) in <bound method tqdm.__del__ of   0%|                                                                                                                                                          | 0/100000 [00:00<?, ?it/s]> ignored
Traceback (most recent call last):
  File "train.py", line 236, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "train.py", line 174, in main
    data, target = next(loader_iter)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 313, in __next__
    indices = next(self.sample_iter)  # may raise StopIteration
StopIteration

**Comment by kazuto1011** [comment]
Have you checked whether the loader can read images? Could you provide output from ```len(dataset)``` or ```len(loader)``` on the ```train.py```?

**Comment by kazuto1011** [comment]
This may be due to the dataset setup. Let me know if you still have a problem.
