### ISSUE TITLE
Output size of the deeplabv3+ model

### ISSUE THREAD

**Issue by Keson96** [kazuto1011/deeplab-pytorch#30]
When I run the deeplab v3+ model in "libs/models/deeplabv3plus.py", the size of output I get is 1 x 21 x 260 x 260, not the input image size (but half). Is that correct? In segmentation, the output usually has the same size as input.

**Comment by kazuto1011** [comment]
Thank you for reporting the issue. Not all models output full-size segmentation but the DeepLab v3 does as you said. That's my mistake. The low-level features were extracted one step behind the original. Fixed #31.

**Comment by Keson96** [comment]
Thank you. Fix #31 also makes the structure more clear. Great.
