### ISSUE TITLE
Make up the gap between reimplementation and official one

### ISSUE THREAD

**Issue by XiaLiPKU** [kazuto1011/deeplab-pytorch#34]
I find in your code, both traning and test need multi-scale input. But as I read, MSC is not necessary for traning. Today I ran an experiment, train_no_MSC.test_with_MSC, and it easily surpassed the official values. The results of my experiments are as bellow:
DeepLabv2(no CRF):

pAcc | mAcc | mIoU | fIoU
65.76 | 45.04 | 34.52 | 50.95

No matter what, thanks for your code.
Your repo is the best reimplementation of deeplab-pytorch, as least in my mind.

**Comment by kazuto1011** [comment]
Thank you for your comment! According to the COCO-Stuff repository, I think the authors applied MSC also in training as the original DeepLab did (see [```train.prototxt```](https://github.com/nightrome/cocostuff10k/blob/master/models/deeplab/cocostuff/config/deeplabv2_resnet101/train.prototxt#L33-L56)).  It contains three duplicated branches. Could you give me a clue/reference to find your opinion?

**Comment by kazuto1011** [comment]
I have changed the data augmentation to make it be close to Caffe implementation.

* A scale factor in image re-scaling is sampled by
    * Before: ```random.uniform(0.5, 1.5)```
    * After: ```random.choice((0.5, 0.75, 1.0, 1.25, 1.5))```
* Changed the subsequent padding back to the previous version.
    * Before: center alignment
    * After: left-top alignment

||CRF?|Pixel Accuracy|Mean Accuracy|Mean IoU|Frequency Weighted IoU|
|:-:|:-:|:-:|:-:|:-:|:-:|
|DeepLab v2<br>(**official**)|No|65.1%|45.5%|34.4%|50.4%|
|DeepLab v2<br>(This repo)|No|65.1%|45.3%|34.4%|50.3%|

I think the gap has been eliminated in this updates. The modified codes will be pushed soon. I'm preparing some scores now.
