### ISSUE TITLE
align_corners for interpolation in eval.py

### ISSUE THREAD

**Issue by XiaLiPKU** [kazuto1011/deeplab-pytorch#37]
https://github.com/kazuto1011/deeplab-pytorch/blob/8b8e60a92417fe87234a9ffc347188721cdfdc39/eval.py#L87

I check the implementation for caffe and pytorch in detail, and find that
you should explicitly set align_corners=True for interpolation in pytorch. As in caffe's Interp layer, align_corners is the default setting. 
Before pytorch 0.4.0, alighn_corners=True is the default setting, but not the case nowaday, after 0.4.0's release.

**Comment by kazuto1011** [comment]
Thank you for reporting the issue. The same is true of the training. I have trained again with ```aligned_corners=True```. Here are the results. I will push the codes and update released models soon.

## COCO-Stuff 10k

* DeepLab v2 without CRF post-processing

||```align_corners```|Pixel Accuracy|Mean Accuracy|Mean IoU|Frequency Weighted IoU|
|:-:|:-:|:-:|:-:|:-:|:-:|
|Official Caffe||65.1%|45.5%|34.4%|50.4%|
|This repository|False|65.1%|45.3%|34.4%|50.3%|
|This repository|True|65.3%|45.3%|34.4%|50.5%|

## COCO-Stuff 164k

* DeepLab v2 without CRF post-processing
* Official result is unavailable

||```align_corners```|Pixel Accuracy|Mean Accuracy|Mean IoU|Frequency Weighted IoU|
|:-:|:-:|:-:|:-:|:-:|:-:|
|This repository|False|65.5%|49.3%|37.4%|49.9%|
|This repository|True|65.7%|49.7%|37.6%|50.0%|

**Comment by kazuto1011** [comment]
Fixed #38
