### ISSUE TITLE
How to use your code on cityscapses

### ISSUE THREAD

**Issue by tonysy** [kazuto1011/deeplab-pytorch#4]
Hi, @kazuto1011  Thanks for your work. I would like to know how to use your code on CityScapes? The init.caffemodel can be used for cityscapes or not?

**Comment by kazuto1011** [comment]
Oh I have misunderstood that the init.caffemodel has been used for coco-sutff training! I think you can train cityscapes images by modifying the #classes of the model and integrating with cityscapes dataloader someone's provided, but sorry I'm not sure about the validity with the COCO pre-trained init.caffemodel. According to the general cityscapes manner, an imagenet pre-trained model should be used, right? I will fix the initialization part with the officially provided init model.
