### ISSUE TITLE
about coco stuff result format ? 

### ISSUE THREAD

**Issue by ranjiewwen** [kazuto1011/deeplab-pytorch#41]
- first thanks you works. 
- i want to use the coco-stuff  Segmentation Results Format ? how can i complete this ? thanks !

- and why you change the labels_2.txt and delete the `0 unlabeled`  ?

**Comment by kazuto1011** [comment]
You can export [prediction](https://github.com/kazuto1011/deeplab-pytorch/blob/master/eval.py#L100) as *.png and then may use the official code to convert to the coco format. I have never done it actually, sorry.

The ```unlabeled``` index is 0 in 10k version while 255 in 164k full version. I don't want to set 0 for the ignore class just to be sure, so the label indices in 10k are shifted in this repository.
https://github.com/kazuto1011/deeplab-pytorch/blob/b763fdb3b8b788f7f11062367ad8ad0c91c70bf1/libs/datasets/cocostuff.py#L174
