### ISSUE TITLE
Code for generating deeplab-pytorch/docs/data.png

### ISSUE THREAD

**Issue by deeponcology** [kazuto1011/deeplab-pytorch#42]
Dear Team,
Where is the code for generating this image? 
I used demo.py which produces separate masks but not a single image stacked with all the masks.

**Comment by kazuto1011** [comment]
To show the ```data.png```, let's run ```libs/datasets/cocostuff.py``` as a script, not a module.

```
python libs/datasets/cocostuff.py
```
