### ISSUE TITLE
About the MIOU in the exp results repo

### ISSUE THREAD

**Issue by JiYuanFeng** [kazuto1011/deeplab-pytorch#45]
Hello！kazuto, thank you for your nice work!
According to the description in the Readme.md:

The label indices range from 0 to 181 and the model outputs a 182-dim categorical distribution, but only 171 classes are supervised with COCO-Stuff.

I want to know is that mean there is no 11 classes label in the coco stuff dataset actually. and your repo MIOU 37.6 is the MIOU of 171 class?

**Comment by kazuto1011** [comment]
Yes exactly.
You can see the description about the removed 11 classes [here](https://github.com/nightrome/cocostuff/blob/master/labels.md).
And I filter out the *empty* classes from scoring in ```metric.py```.

**Comment by gulleh** [comment]
Will it be the same as multiplying the mIoU with 182 classes by (182/171)?
