### ISSUE TITLE
"main.py test" running slowly

### ISSUE THREAD

**Issue by xaibeing** [kazuto1011/deeplab-pytorch#47]
I run "main.py test" on cloud GPU Tesla P100-PCIE-16GB and got 39.00s/it, with the config BATCH_SIZE 16 and NUM_WORKERS 8 and no CRF. That's 2.5s/image.
I tried some other BATCH_SIZE and NUM_WORKERS, and still about 2.5s/image. Is this situation normal？

(deeplab-pytorch) [dev@ecs-6f75 deeplab-pytorch]$ python main.py test --config config/cocostuff164k.yaml --model-path /data/model/deeplab-pytorch-master/cocostuff164k_iter100k.pth
Mode: test
cuda = True
Device: Tesla P100-PCIE-16GB

dataset = Dataset CocoStuff164k
    Number of datapoints: 5000
    Split: val2017
    Root Location: /data/data/COCO/2017

len(loader) = 313
 20%|████████████████▎                                                               | 64/313 [41:36<2:41:50, 39.00s/it]

GPU usage：
![image](https://user-images.githubusercontent.com/7598262/51649396-3b8fb880-1fbf-11e9-87bb-ab2df06e4ab8.png)

**Comment by kazuto1011** [comment]
What if with ```torch.backends.cudnn.enabled = False```?
I was also in a similar situation with the current release PyTorch.
Disabling cuDNN made it on 7.5 s/it from 31 s/it in my case.

**Comment by xaibeing** [comment]
@kazuto1011 thank you very much! 
Setting `torch.backends.cudnn.enabled = False` improve the speed from 39.00s/it to 7.99s/it.

My envirioment:
CentOS 7.5
python 3.6.7
torch.__version__ = '1.0.0'
cuda9.2_0
cudnn-7.2.1

**Comment by kazuto1011** [comment]
I'm sorry I haven't solved this issue yet. The current workaround is to disable cuDNN, or auto-tune it with ```torch.backends.cudnn.benchmark = True``` if ```torch.backends.cudnn.version()``` returns any numbers but None. Note that the benchmark option can be useful only when the input size is fixed.

**Comment by kazuto1011** [comment]
Let me close this issue because it's not due to this repo. #49 includes the cudnn option now.
