### ISSUE TITLE
Crashing on test

### ISSUE THREAD

**Issue by fabiopoiesi** [kazuto1011/deeplab-pytorch#52]
Hi Kazuto,

For some reason when I launch the test on coco stuff 10k, the script crashes at about 38%. This is the error  message I got:

```
python main.py test --config config/cocostuff10k.yaml --model-path data/models/deeplab_resnet101/cocostuff10k/checkpoint_final.pth
Mode: test
Device: TITAN X (Pascal)
/hardmnt/kraken0/home/poiesi/data/research/deeplearning/deeplab-pytorch/libs/utils/metric.py:21: RuntimeWarning: invalid value encountered in true_divide
  acc_cls = np.diag(hist) / hist.sum(axis=1)
/hardmnt/kraken0/home/poiesi/data/research/deeplearning/deeplab-pytorch/libs/utils/metric.py:23: RuntimeWarning: invalid value encountered in true_divide
  iu = np.diag(hist) / (hist.sum(axis=1) + hist.sum(axis=0) - np.diag(hist))
```
Do you know what it might be due to?

**Comment by kazuto1011** [comment]
The warning message is due to the 11 empty classes in computing scores but I don't think they caused the crash. Is there any other message?

**Comment by fabiopoiesi** [comment]
I pasted the whole message. From the call of the function to the end.

**Comment by kazuto1011** [comment]
I guess this has produced ```data/models/deeplab_resnet101/cocostuff10k/checkpoint_final.json```. Could you check the results in it?

**Comment by fabiopoiesi** [comment]
This is the content of checkpoint_final.json

{
    "Class IoU": {
        "0": 0.21776031472603485,
        "1": 0.0075313480134847,
        "2": 0.010529395062124174,
        "3": 0.1142311820758051,
        "4": 0.15680853247422566,
        "5": 0.1553699686097208,
        "6": 0.07940892360365252,
        "7": 0.0239045048910893,
        "8": 0.05438100973147119,
        "9": 0.0,
        "10": 0.03285660560156375,
        "11": NaN,
        "12": 0.16322006007399154,
        "13": 0.0,
        "14": 0.00028673932541516047,
        "15": 0.030766132922782626,
        "16": 0.0716802555359043,
        "17": 0.0014689395178156346,
        "18": 0.010782807472347262,
        "19": 0.011346585851735685,
        "20": 0.026164698597558583,
        "21": 0.06877453791913118,
        "22": 0.00143959185348306,
        "23": 0.3507167152475488,
        "24": 0.20333232073456453,
        "25": NaN,
        "26": 0.0,
        "27": 0.0701295842848103,
        "28": NaN,
        "29": NaN,
        "30": 0.0,
        "31": 0.0,
        "32": 0.000381445775248638,
        "33": 0.0,
        "34": 0.0,
        "35": 0.0,
        "36": 0.0,
        "37": 0.019206799118172826,
        "38": 0.0,
        "39": 0.0,
        "40": 0.0,
        "41": 0.0,
        "42": 0.0,
        "43": 0.001446426652141677,
        "44": NaN,
        "45": 0.0,
        "46": 0.0,
        "47": 0.0,
        "48": 0.0,
        "49": 0.0,
        "50": 0.017704600886703697,
        "51": 0.04472283690999325,
        "52": 0.000587367305130152,
        "53": 0.028867061857040327,
        "54": 0.009565165586586263,
        "55": 0.06361377289888306,
        "56": 0.021537571664313297,
        "57": 0.00463431971209009,
        "58": 0.3138594939238026,
        "59": 0.03272228486405431,
        "60": 0.03695458825309139,
        "61": 0.00648648715888255,
        "62": 0.007724832097666072,
        "63": 0.007808366769259286,
        "64": 0.01715783065240214,
        "65": NaN,
        "66": 0.14126218274588456,
        "67": NaN,
        "68": NaN,
        "69": 0.005970357292199043,
        "70": NaN,
        "71": 0.06696863941210839,
        "72": 0.02489182905217069,
        "73": 0.0,
        "74": 0.0,
        "75": 0.01797214196943041,
        "76": 0.0,
        "77": 0.0009338764960953866,
        "78": 0.009952751886211229,
        "79": 0.0,
        "80": 1.5043385122693849e-05,
        "81": 0.0005410314977572538,
        "82": NaN,
        "83": 0.001031146877809695,
        "84": 0.004699186494319448,
        "85": 0.00013389031705227078,
        "86": 0.0,
        "87": 0.0,
        "88": 0.0,
        "89": 0.0,
        "90": NaN,
        "91": 0.056369384428375136,
        "92": 0.0,
        "93": 0.0,
        "94": 0.0,
        "95": 0.14702148817247565,
        "96": 0.005678723641883982,
        "97": 0.01592615198746547,
        "98": 0.0,
        "99": 0.0,
        "100": 0.0005946183927692746,
        "101": 0.06298477004626131,
        "102": 0.0,
        "103": 0.0,
        "104": 0.0,
        "105": 0.3605711459480303,
        "106": 0.0004574677891267208,
        "107": 0.05640430009453367,
        "108": 0.001547697297915208,
        "109": 0.026453185264671046,
        "110": 0.10525516143999408,
        "111": 5.762372264522046e-05,
        "112": 0.055451798506117055,
        "113": 0.0,
        "114": 2.1102500118701564e-05,
        "115": 0.0,
        "116": 0.0024931008309868443,
        "117": 0.13713604858903805,
        "118": 0.00567750255460293,
        "119": 0.0,
        "120": 0.05980029593124254,
        "121": 0.0,
        "122": 0.0014643086267089461,
        "123": 0.45892172781275736,
        "124": 0.030677207081064143,
        "125": 0.016552556139865848,
        "126": 0.04505122597867671,
        "127": 0.020425630349294472,
        "128": 0.0,
        "129": 0.0009288202197017058,
        "130": 0.0,
        "131": 0.001113178098512102,
        "132": 0.0004951156107957748,
        "133": 0.0,
        "134": 0.03927793738220278,
        "135": 0.0,
        "136": 0.0,
        "137": 0.0005063789276919827,
        "138": 0.0,
        "139": 0.040448710375644924,
        "140": 0.0,
        "141": 0.006495504728168809,
        "142": 0.0,
        "143": 0.0,
        "144": 0.33246302891435864,
        "145": 0.0003081183754549277,
        "146": 0.08061405889293899,
        "147": 0.0014805826043085284,
        "148": 0.2506697355571653,
        "149": 0.0007117219584953721,
        "150": 0.0,
        "151": 0.0,
        "152": 0.0,
        "153": 0.1448627984788912,
        "154": 0.32208121809705126,
        "155": 0.0,
        "156": 0.5189216159996083,
        "157": 0.0,
        "158": 0.38734605921487736,
        "159": NaN,
        "160": 0.0,
        "161": 0.0,
        "162": 0.002990462371489746,
        "163": 0.0011291770328260575,
        "164": 0.000993882897356723,
        "165": 0.0,
        "166": 0.0,
        "167": 0.0,
        "168": 0.3351500439016227,
        "169": 0.005048672073477044,
        "170": 0.1110446677081931,
        "171": 0.0,
        "172": 0.25354950540678434,
        "173": 0.0,
        "174": 0.0029059427391312782,
        "175": 0.009869441948219797,
        "176": 0.0032671081677704194,
        "177": 0.03667632471765454,
        "178": NaN,
        "179": 0.009519428126548234,
        "180": 0.07582460584369584,
        "181": 0.0
    },
    "Frequency Weighted IoU": 0.17846328817680418,
    "Mean Accuracy": 0.07708677265415062,
    "Mean IoU": 0.043916758302574806,
    "Pixel Accuracy": 0.3326036556498822
}

**Comment by kazuto1011** [comment]
Hmm, no-message crashing is strange to me. Could you investigate where the code crashes?

**Comment by fabiopoiesi** [comment]
OK. I'll have a look. Thanks.
