### ISSUE TITLE
SegmentationAug file link problem

### ISSUE THREAD

**Issue by bigpicturejh** [kazuto1011/deeplab-pytorch#54]
The dataset preparation link for "SegmentationAug" is no more exist
[https://ucla.app.box.com/s/rd9z2xvwsfpksi7mi08i2xqrj7ab4keb/file/55053033642](url)

Where can I download that files for VOC12 dataset

**Comment by kazuto1011** [comment]
I have verified the file `list.zip` could be downloaded from the link again.
Couldn't you access a blue download button?

**Comment by bigpicturejh** [comment]
> I have verified the file `list.zip` could be downloaded from the link again.
> Couldn't you access a blue download button?

Yes, When I click that link, the page said that "the shared file is removed"
If possible, could you share that file through the GoogleDrive or DropBox?

Thanks

**Comment by kazuto1011** [comment]
[list.zip](https://github.com/kazuto1011/deeplab-pytorch/files/2945588/list.zip) :)

**Comment by bigpicturejh** [comment]
Thanks! It's working

**Comment by kazuto1011** [comment]
Updated the README

**Comment by bigpicturejh** [comment]
I have another question for training.

When I run the main.py the below error message appeared.

I trying to train the network via VOC 2012 dataset.

[image: image.png]

Do you have any idea for next step what I have to do?

😀


2019년 3월 8일 (금) 오후 9:12, Kazuto Nakashima <notifications@github.com>님이 작성:

**Comment by kazuto1011** [comment]
I can't see any image. Could you send me again?

**Comment by bigpicturejh** [comment]
I send the error log again

2019년 3월 8일 (금) 오후 11:00, Kazuto Nakashima <notifications@github.com>님이 작성:

**Comment by katoabc123** [comment]
qweqwe
