### ISSUE TITLE
Invalid split name: train_aug

### ISSUE THREAD

**Issue by katoabc123** [kazuto1011/deeplab-pytorch#55]
When I try to train the VOC2012 dataset. It show the error : ValueError: Invalid split name: train_aug

It happen in the voc.py file line 43:
raise ValueError("Invalid split name: {}".format(self.split))

I tried to set the root to the "/data/datasets/voc12/VOCdevkit" but it still cannot fix the problem.

What should I do?

**Comment by kazuto1011** [comment]
What is a value of your `COFNIG.DATASET.NAME` set in a config file? If you want to train on the `train_aug` set, please use `vocaug` not just `voc`.

https://github.com/kazuto1011/deeplab-pytorch/blob/79cb3900bea41aa45cd9848bcd6b9e7e8177e6d0/main.py#L118-L128

**Comment by katoabc123** [comment]
Thank you very much. It works.
