### ISSUE TITLE
hubconf.py KeyError/NotImplementedError/TypeError

### ISSUE THREAD

**Issue by otaj** [kazuto1011/deeplab-pytorch#58]
Hi, hubconf.py is wrong -- either you get a KeyError if you don't include ``pretrained`` in ``kwargs`` or you get a NotImplementedError if ``pretrained`` is in ``kwargs`` and evaluates to ``True`` or you get a TypeError (``TypeError: __init__() got an unexpected keyword argument 'pretrained'``) from line 26 if you include ``pretrained`` in ``kwargs`` that evaluates to ``False``

That means, that right now, hubconf.py is unusable, an easy fix would be to either accept unknown kwargs by DeepLabV2 constructor or check for presence of the key before checking for True value of ``kwargs['pretrained']`` on line 17 in hubconf.py

**Comment by kazuto1011** [comment]
Thank you for reporting! Fixed it #59.
