### ISSUE TITLE
About the Train

### ISSUE THREAD

**Issue by BEYBB7** [kazuto1011/deeplab-pytorch#6]
Thanks for your work! Could you please provide the training scripts of the DeepLab v3/v3+ model? Thank you very much!

**Comment by kazuto1011** [comment]
The training procedures written in the v3/v3+ paper are different from the v2, so I haven't tried yet. I'm sorry but I have no plan to implement that for now. Please use the existing ```train.py```.
```python
from libs.models import init_weights
...

model = DeepLabV3Plus_ResNet101_MSC(n_classes=CONFIG.N_CLASSES)
init_weights(model)
state_dict = torch.load(CONFIG.INIT_MODEL)
model.load_state_dict(state_dict, strict=False)
...

model.train()
model.module.scale.freeze_bn()
```
