### ISSUE TITLE
The ImageNet training

### ISSUE THREAD

**Issue by katoabc123** [kazuto1011/deeplab-pytorch#61]
I am confused about the ImageNet training.
Is your model architectures of ImageNet is resnet101?
Thank you very much

**Comment by kazuto1011** [comment]
Yes, true. The ResNet-101 model is from the author's page and it has also been fine-tuned on COCO dataset. I will update README to be made clear.

**Comment by haochenheheda** [comment]
Hi, I want to know if you have the pre-trained model on ImageNet without fine-tuned on COCO. Thanks!

**Comment by kazuto1011** [comment]
No, I don't have it. Why don't you start from torchvision model, although it's a bit different from the caffe-deeplab? https://github.com/kazuto1011/deeplab-pytorch/issues/33#issuecomment-421825911
