### ISSUE TITLE
How can I use the ImageNet-pretrained weights for PASCAL VOC 2012?

### ISSUE THREAD

**Issue by bityangke** [kazuto1011/deeplab-pytorch#67]
How can I use the ImageNet-pretrained weights for PASCAL VOC 2012?
Thanks very much!

**Comment by kazuto1011** [comment]
Unfortunately, there are no ImageNet weights loadable to ResNet of this repository.
You can transform torchvision models to DeepLab.
For ResNet, please refer to https://github.com/kazuto1011/deeplab-pytorch/issues/33#issuecomment-421825911.

**Comment by bityangke** [comment]
Thank you very much！
Close this！
