### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by wukaoliu** [kazuto1011/deeplab-pytorch#69]
How many iterations does this train have to achieve the same effect? I trained v2 about 20,000 iterations, and tested the results on the training set very poorly.

**Comment by kazuto1011** [comment]
**100,000** for COCO-Stuff 160k, **20,000** for COCO-Stuff 10k, and **20,000** for PASCAL VOC, as written in README. Could you provide more information about a dataset, command you run, and any modifications?

**Comment by wukaoliu** [comment]
Thanks for your reply. I have found the issue.
