### ISSUE TITLE
GPU memory usage is very high

### ISSUE THREAD

**Issue by Kenneth-X** [kazuto1011/deeplab-pytorch#74]
my gpu:Tesla P100-PCIE, 16276MiB Memory

my batch size =2 and gpu id =0,1 (1 image for each gpu) ,input size=(513,513)
when the training  is start ,the memory usage is very high(12756MiB / 16276MiB) and drop to normal after a while(4689MiB / 16276MiB)

This makes  a very low input size, as i can not input a biger size(1000,1000) beacuse memory usage will blow up at first

what makes this happen? Can it be optimised?  how can i solve it

**Comment by kazuto1011** [comment]
It seems that cuDNN looked for the optimal conv algorithm at the very first iteration (when the input size changes, to be precise). Please try disabling the benchmark mode.
https://github.com/kazuto1011/deeplab-pytorch/blob/79cb3900bea41aa45cd9848bcd6b9e7e8177e6d0/main.py#L115

**Comment by Kenneth-X** [comment]
Yeah, it worked
Really help me a lot,  thank you for your help
