### ISSUE TITLE
will the codes for converting caffeeweights into pytorch weights work on DeepLabV3+ ?

### ISSUE THREAD

**Issue by kkhuang1990** [kazuto1011/deeplab-pytorch#75]
hi, thank you very much for sharing your codes

I roughly read the convert.py file and I am wondering whether this function works well on DeepLabV3+ or not, best regards

**Comment by kazuto1011** [comment]
It works for nothing but the v2 model produced by [the author's Caffe](https://bitbucket.org/aquariusjay/deeplab-public-ver2/src/master/). FYI: https://github.com/kazuto1011/deeplab-pytorch/issues/25
