### ISSUE TITLE
checkpoint_final.pth doe not exit

### ISSUE THREAD

**Issue by wwwmmmqqq** [kazuto1011/deeplab-pytorch#81]
deeplab-pytorch/data/models/${DATASET}/deeplabv2_resnet101_msc/*/checkpoint_final.pth   doe not exit

**Comment by kazuto1011** [comment]
Does it mean the training script did not produce `checkpoint_final.pth` anywhere or the path is wrong? Could you tell me know if you ran the `scripts/train_eval.sh` intact or any custom scripts?

**Comment by wwwmmmqqq** [comment]
> Does it mean the training script did not produce `checkpoint_final.pth` anywhere or the path is wrong? Could you tell me know if you ran the `scripts/train_eval.sh` intact or any custom scripts?

It is wrong when the deeplab pytorch/data/models/${DATASET}/deeplabv2_resnet101_msc/*/checkpoint_final.pth was running . I do not find the code of downloading the checkpoint_final.pth.

**Comment by kazuto1011** [comment]
The parameter file `checkpoint_final.pth` is not available until [this line of training](https://github.com/kazuto1011/deeplab-pytorch/blob/master/scripts/train_eval.sh#L11-L12) is finished. If you want to use the pre-trained parameters, please visit [here](https://github.com/kazuto1011/deeplab-pytorch#performance) in README and find the link to download it.

**Comment by wwwmmmqqq** [comment]
> The parameter file `checkpoint_final.pth` is not available until [this line of training](https://github.com/kazuto1011/deeplab-pytorch/blob/master/scripts/train_eval.sh#L11-L12) is finished. If you want to use the pre-trained parameters, please visit [here](https://github.com/kazuto1011/deeplab-pytorch#performance) in README and find the link to download it.

There  are three .pth files. Do I download all of them?

**Comment by wwwmmmqqq** [comment]
> The parameter file `checkpoint_final.pth` is not available until [this line of training](https://github.com/kazuto1011/deeplab-pytorch/blob/master/scripts/train_eval.sh#L11-L12) is finished. If you want to use the pre-trained parameters, please visit [here](https://github.com/kazuto1011/deeplab-pytorch#performance) in README and find the link to download


did the errors appears because  [the line of training](https://github.com/kazuto1011/deeplab-pytorch/blob/master/scripts/train_eval.sh#L11-L12)  did not successfully run?

**Comment by kazuto1011** [comment]
> did the errors appears because [the line of training](https://github.com/kazuto1011/deeplab-pytorch/blob/master/scripts/train_eval.sh#L11-L12) did not successfully run?

I guess so.
