### ISSUE TITLE
Image upload not working

### ISSUE THREAD

**Issue by bitafro** [kazuto1011/deeplab-pytorch#83]
Hi 
I love http://nvidia-research-mingyuliu.com/gaugan/
My kid is doing a contest in hive.blog/created/gaugan and after upgrade the upload image for segmentation is not working.
I hope I'm in the right place to put this issue
Thanks

**Comment by kazuto1011** [comment]
Sorry, I'm not involved in GauGAN. I think the [SPADE repository](https://github.com/NVlabs/SPADE) is the better place to report the server-side issue.

**Comment by kazuto1011** [comment]
The site seems to be working now.
