### ISSUE TITLE
resnet          # Downsampling is only in the first block

### ISSUE THREAD

**Issue by wuzuowuyou** [kazuto1011/deeplab-pytorch#88]
in your resnet.py code 
line87     # Downsampling is only in the first block
https://github.com/kazuto1011/deeplab-pytorch/blob/4219467fa5de07985f834f1bd8c04c186dc8f6d8/libs/models/resnet.py#L87

but Downsampling is only in the last block in official resnet. 
so, why you "Downsampling is only in the first block"

**Comment by kazuto1011** [comment]
If you meant MSRA ResNet by "official resnet", I think downsampling in the first block is correct.
This is the architecture diagram from [here](https://github.com/KaimingHe/deep-residual-networks). You can see strided-downsampling resides in the first block.
http://ethereon.github.io/netscope/#/gist/b21e2aae116dc1ac7b50

As far as I know, [TF-Slim ResNet](https://github.com/tensorflow/models/blob/master/research/slim/nets/resnet_v1.py) downsamples in the last block, however, I'm not sure where the change is from.
There are many types of architectures of ResNet and my code follows the DeepLab version written in Caffe, not the official. 
It is different from MSRA's one, FAIR's one, and the torchvision model in some other parts.

**Comment by wuzuowuyou** [comment]
Thank you for your well-founded answer, thank you!
