### ISSUE TITLE
A question about MS-COCO pre-trained weight

### ISSUE THREAD

**Issue by johnnylu305** [kazuto1011/deeplab-pytorch#89]
This repository is amazing and it works very well. I have a question about MS-COCO pre-trained weight. Which datasets did they use to pre-train the weight, MS-COCO segmentation, or MS-COCO classification dataset? That is to say, they initialize DeepLab V2 ResNet101 from a pre-trained MS-COCO weight and then finetune it on Pascal VOC12. Do you know which datasets(segmentation or classification) they use to pre-train it?

**Comment by kazuto1011** [comment]
I think COCO segmentation set. The COCO-trained model is from [the authors' another work](https://arxiv.org/pdf/1502.02734.pdf) (refer to *Cross-Pretrain* setting). I provided the reference architecture for the COCO-trained model in `libs.models.deeplabv1.DeepLabV1`.

```sh
# You can verify the COCO segmentation.
python demo.py single -c configs/coco.yaml -m data/models/coco/deeplabv1_resnet101/caffemodel/deeplabv1_resnet101-coco.pth -i image.jpg
```
