### ISSUE TITLE
A question about pascal voc pre-trained model

### ISSUE THREAD

**Issue by RumengYi** [kazuto1011/deeplab-pytorch#90]
Hi, why you load train2_iter_20000.caffemodel instead of init.caffemodel from http://liangchiehchen.com/projects/released/deeplab_aspp_resnet101/prototxt_and_model.zip as initial weights? I think the latter should be loaded.

**Comment by kazuto1011** [comment]
The model is initialized with `init.caffemodel`.
https://github.com/kazuto1011/deeplab-pytorch/blob/4219467fa5de07985f834f1bd8c04c186dc8f6d8/main.py#L147
https://github.com/kazuto1011/deeplab-pytorch/blob/4219467fa5de07985f834f1bd8c04c186dc8f6d8/configs/voc12.yaml#L34

The `deeplabv1_resnet101-coco.pth` file are converted from `init.caffemodel` as mentioned in [README](https://github.com/kazuto1011/deeplab-pytorch#download-pre-trained-caffemodels).

**Comment by RumengYi** [comment]
Thank you for your reply, but on PASCAL VOC 2012, the model is initialized with train2_iter_20000.caffemodel, https://github.com/kazuto1011/deeplab-pytorch/blob/master/convert.py#L170, why you load train2_iter_20000.caffemodel instead of init.caffemodel?

**Comment by kazuto1011** [comment]
Yes, `python convert.py --dataset voc12` loads `train2_iter_20000.caffemodel` trained on PASCAL VOC 2012 already, however, the converted weights are not used in training. This is just for those who do not want to train by themselves.
Please run `python convert.py --dataset coco` to produce the initial weights from `init.caffemodel`.
