### ISSUE TITLE
Apply multi-scale during testing

### ISSUE THREAD

**Issue by TyroneLi** [kazuto1011/deeplab-pytorch#92]
Thanks, I noticed that the code only support one scale image inference, could we implement multi-scale image size for inference?

**Comment by kazuto1011** [comment]
The models named with "MSC" do multi-scale inference. See `libs/models/msc.py`.

https://github.com/kazuto1011/deeplab-pytorch/blob/4219467fa5de07985f834f1bd8c04c186dc8f6d8/libs/models/__init__.py#L33-L39
