### ISSUE TITLE
pascal voc2012 dataset

### ISSUE THREAD

**Issue by doublelaffe** [kazuto1011/deeplab-pytorch#96]
Thanks for your projects,and I have learnt a lot ,but I met a small question about the 'configs/voc12.yaml',so after I download thevoc2012 dataset, where should I put this dataset and how to modify the parameters of 'voc12.yaml'.I am looking forward to reciving your answer.

**Comment by kazuto1011** [comment]
Have you checked [this README](https://github.com/kazuto1011/deeplab-pytorch/blob/master/data/datasets/voc12/README.md)?
