### ISSUE TITLE
How to refer to your work?

### ISSUE THREAD

**Issue by wuhao9714** [kazuto1011/deeplab-pytorch#99]
Hi,
The code is very helpful to my work. How can I cite your work in my paper? Quote 'deeplab' or paste the URL, or whatever?

**Comment by kazuto1011** [comment]
Thank you for using my codes! I have found three types:
- Paste the URL in an official code repository.
- Paste the URL in a footnote.
- Cite with the bibtex like below.

```
@misc{nakashima2018deeplab,
  author       = {Kazuto Nakashima},
  title        = {deeplab-pytorch},
  publisher    = {GitHub},
  journal      = {GitHub repository},
  howpublished = {\url{https://github.com/kazuto1011/deeplab-pytorch}},
  year         = {2018},
  commit       = {}
}
```

The last one might be proper but few. You can choose whatever you like.
